export const LAB_TEST_CATEGORIES = [
  {
    id: "general_enzyme_cardiac",
    name: "General / Enzyme / Cardiac Tests",
    tests: [
      {
        id: "ammonia",
        name: "Ammonia",
        unit: "µg/dL",
        normalValue: "15–45 µg/dL",
        criticalValue: ">150 µmol/L",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "crp",
        name: "CRP",
        unit: "mg/L",
        normalValue: "<5 mg/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "ldh",
        name: "LDH",
        unit: "U/L",
        normalValue: "140–240 U/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "ck_mb",
        name: "CK-MB",
        unit: "U/L",
        normalValue: "5–25 U/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "amylase",
        name: "Amylase",
        unit: "U/L",
        normalValue: "30–110 U/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "lipase",
        name: "Lipase",
        unit: "U/L",
        normalValue: "0–50 U/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "iron",
        name: "Iron",
        unit: "µg/dL",
        normalMale: "50–150 µg/dL",
        normalFemale: "35–145 µg/dL",
        normalValue: "50–150 µg/dL",
        criticalValue: "≥350 µg/dL",
        sexDependent: true,
        ageDependent: false,
      },
      {
        id: "ferritin",
        name: "Ferritin",
        unit: "µg/dL",
        normalMale: "50–150 µg/dL",
        normalFemale: "35–145 µg/dL",
        normalValue: "50–150 µg/dL",
        criticalValue: null,
        sexDependent: true,
        ageDependent: false,
      },
      {
        id: "uibc",
        name: "UIBC",
        unit: "µg/dL",
        normalValue: "111–343 µg/dL",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "troponin_i",
        name: "Troponin I",
        unit: "ng/mL",
        normalValue: "<0.04 ng/mL",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
    ],
  },
  {
    id: "vitamins_immunology_other",
    name: "Vitamins / Immunology / Other Tests",
    tests: [
      {
        id: "vitamin_d",
        name: "Vitamin D",
        unit: "As written in reference",
        normalValue: "30–100 mg/mL*",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "anti_ccp",
        name: "Anti-CCP",
        unit: "U/mL",
        normalValue: "<20 U/mL",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "cholinesterase",
        name: "Cholinesterase",
        unit: "U/L",
        normalValue: "4,500–11,500 U/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "homocysteine",
        name: "Homocysteine",
        unit: "µmol/L",
        normalValue: "5–15 µmol/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "ph_abg",
        name: "pH - ABG",
        unit: "pH",
        normalValue: "—",
        criticalValue: "≤7.0",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "ph_vbg",
        name: "pH - VBG",
        unit: "pH",
        normalValue: "—",
        criticalValue: "≤7.0",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "ph_cord_blood",
        name: "pH - Cord Blood",
        unit: "pH",
        normalValue: "—",
        criticalValue: "≤7.0",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "vitamin_b12",
        name: "Vitamin B12 (Serum)",
        unit: "pg/mL",
        normalValue: "160–1000 pg/mL",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "bicarbonate",
        name: "Bicarbonate (Whole Blood)",
        unit: "mmol/L",
        normalValue: "—",
        criticalValue: "≤10 mmol/L or ≥40 mmol/L",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "co_hb",
        name: "CO-Hb",
        unit: "%",
        normalValue: "—",
        criticalValue: ">20.1%",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "meth_hb",
        name: "Meth-Hb",
        unit: "%",
        normalValue: "—",
        criticalValue: ">3%",
        sexDependent: false,
        ageDependent: false,
      },
    ],
  },
  {
    id: "plasma_glucose",
    name: "Plasma Glucose",
    tests: [
      {
        id: "plasma_glucose_f",
        name: "Plasma Glucose (F)",
        unit: "mg%",
        normalValue: "70–110 mg%",
        criticalValue: null,
        ageRules: [
          { maxAgeDays: 2, critical: "≤35 or ≥200" },
          { maxAgeDays: 30, critical: "≤40 or ≥200" },
          { maxAgeDays: 365, critical: "≤40 or ≥300" },
          { maxAgeDays: 6205, critical: "≤55 or ≥300" },
          { maxAgeDays: Infinity, critical: "≤55 or ≥450" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
      {
        id: "plasma_glucose_pm",
        name: "Plasma Glucose (PM)",
        unit: "mg%",
        normalValue: "110–140 mg%",
        criticalValue: null,
        ageRules: [
          { maxAgeDays: 2, critical: "≤35 or ≥200" },
          { maxAgeDays: 30, critical: "≤40 or ≥200" },
          { maxAgeDays: 365, critical: "≤40 or ≥300" },
          { maxAgeDays: 6205, critical: "≤55 or ≥300" },
          { maxAgeDays: Infinity, critical: "≤55 or ≥450" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
      {
        id: "plasma_glucose_r",
        name: "Plasma Glucose (R)",
        unit: "mg%",
        normalValue: "<200 mg%",
        criticalValue: null,
        ageRules: [
          { maxAgeDays: 2, critical: "≤35 or ≥200" },
          { maxAgeDays: 30, critical: "≤40 or ≥200" },
          { maxAgeDays: 365, critical: "≤40 or ≥300" },
          { maxAgeDays: 6205, critical: "≤55 or ≥300" },
          { maxAgeDays: Infinity, critical: "≤55 or ≥450" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
    ],
  },
  {
    id: "kft",
    name: "KFT",
    tests: [
      {
        id: "blood_urea",
        name: "Blood Urea",
        unit: "mg%",
        normalValue: "15–45 mg%",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_creatinine",
        name: "S. Creatinine",
        unit: "mg%",
        normalValue: "0.6–1.2 mg%",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_sodium",
        name: "S. Sodium (Na⁺)",
        unit: "mEq/L",
        normalValue: "135–145 mEq/L",
        criticalValue: "≤125 or ≥160 mmol/L",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_potassium",
        name: "S. Potassium (K⁺)",
        unit: "mEq/L",
        normalValue: "3.5–5.0 mEq/L",
        criticalValue: null,
        ageRules: [
          { maxAgeDays: 7, critical: "<2.5 or >6.0 mmol/L" },
          { maxAgeDays: Infinity, critical: "<3.0 or >6.0 mmol/L" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
    ],
  },
  {
    id: "lft",
    name: "LFT",
    tests: [
      {
        id: "sgot",
        name: "SGOT",
        unit: "IU/L",
        normalValue: "0–41 IU/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "sgpt",
        name: "SGPT",
        unit: "IU/L",
        normalValue: "0–45 IU/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_alp",
        name: "S. ALP",
        unit: "IU/L",
        normalValue: "25–140 IU/L",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_total_protein",
        name: "S. Total Protein",
        unit: "gm%",
        normalValue: "6.0–8.0 gm%",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_albumin",
        name: "S. Albumin",
        unit: "gm%",
        normalValue: "3.5–5.0 gm%",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "s_total_bilirubin",
        name: "S. Total Bilirubin",
        unit: "mg%",
        normalValue: "0.2–1.2 mg%",
        criticalValue: null,
        ageRules: [
          { maxAgeHours: 24, critical: "≥8 mg/dL" },
          { maxAgeHours: 48, critical: "≥13 mg/dL" },
          { maxAgeHours: 84, critical: "≥17 mg/dL" },
          { maxAgeHours: 720, critical: "≥15 mg/dL" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
      {
        id: "s_direct_bilirubin",
        name: "S. Direct Bilirubin",
        unit: "mg%",
        normalValue: "0.1–0.4 mg%",
        criticalValue: null,
        sexDependent: false,
        ageDependent: false,
      },
    ],
  },
  {
    id: "ions",
    name: "Ions",
    tests: [
      {
        id: "ca",
        name: "Ca²⁺",
        unit: "mg/dL",
        normalValue: "8–12 mg/dL",
        criticalValue: "≤6.5 or ≥13 mg/dL",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "mg",
        name: "Mg²⁺",
        unit: "mg/dL",
        normalValue: "1.7–2.2 mg/dL",
        criticalValue: "≤1.0 or ≥3.5 mg/dL",
        sexDependent: false,
        ageDependent: false,
      },
      {
        id: "po4",
        name: "PO₄³⁻",
        unit: "mg/dL",
        normalValue: "2.5–4.5 mg/dL",
        criticalValue: null,
        ageRules: [
          { maxAgeYears: 3, critical: "≤2.5 mg/dL" },
          { maxAgeYears: 12, critical: "≤2.0 mg/dL" },
          { maxAgeYears: Infinity, critical: "≤1.5 mg/dL" },
        ],
        sexDependent: false,
        ageDependent: true,
      },
      {
        id: "ica",
        name: "iCa",
        unit: "mg/dL",
        normalValue: "4.5–5.6 mg/dL",
        criticalValue: "<0.8 or >1.6 mg/dL",
        sexDependent: false,
        ageDependent: false,
      },
    ],
  },
];

export const SEX_OPTIONS = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];

export const AGE_UNIT_OPTIONS = [
  { label: "Years", value: "years" },
  { label: "Months", value: "months" },
  { label: "Days", value: "days" },
];
